config/routes.rb
Options::Application.routes.draw do
  
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  resources :options

  root :to => 'home#index'

end

app/models/option.rb
class Option < ActiveRecord::Base
  attr_accessible :price, :strike, :term, :volatility, :dividend, :riskfree, :user_id, :title ,:call_price ,:put_price
  validates_presence_of :price, :strike, :term, :volatility, :dividend, :riskfree, :title
  validates_numericality_of :price, :strike, :term, :volatility, :dividend, :riskfree
  belongs_to :user
  
  def self.black_scholes_call_price(price,strike,riskfree,dividend,term,volatility)
    time_sqrt = Math.sqrt(term)
    d1 = (Math.log(price/strike)+((riskfree/100)-(dividend/100)+(((volatility/100)**2)/2))*term)/((volatility/100)*Math.sqrt(term))
    nd1 = Statistics2.normaldist(d1)
    d2 = d1 - (volatility/100)*term**0.5
    nd2 = Statistics2.normaldist(d2)
    call = (Math.exp((0-(dividend/100))*term)*price*nd1)-strike*(Math.exp((-(riskfree/100))*term))*nd2
    put  = (strike*(Math.exp(-riskfree*time_sqrt)*nd2 - price*nd1))
    return call,put
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  has_many :options
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  

  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  
  end
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController
  
    before_filter :authenticate_user!
  
  # GET /options
  # GET /options.json
  def index
    @options = current_user.options.order("created_at DESC").page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @options }
    end
  end

  # GET /options/1
  # GET /options/1.json
  def show
    @option = current_user.options.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @option }
    end
  end

  # GET /options/new
  # GET /options/new.json
  def new
    @option = current_user.options.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @option }
    end
  end

  # GET /options/1/edit
  def edit
    @option = current_user.options.find(params[:id])
  end

  # POST /options
  # POST /options.json
  def create
    @option = current_user.options.build(params[:option])
    option_params = params[:option]
    @prices = Option.black_scholes_call_price(option_params[:price].to_i,option_params[:strike].to_i,option_params[:riskfree].to_i,option_params[:dividend].to_f,option_params[:term].to_f,option_params[:volatility].to_f) 
    @option.call_price = @prices[0]
    @option.put_price = @prices[1]
    respond_to do |format|
      if @option.save
        format.html { redirect_to @option, notice: 'Option was successfully created.' }
        format.json { render json: @option, status: :created, location: @option }
      else
        format.html { render action: "new" }
        format.json { render json: @option.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /options/1
  # PUT /options/1.json
  def update
    @option = Option.find(params[:id])
    option_params = params[:option]
    @prices = Option.black_scholes_call_price(option_params[:price].to_i,option_params[:strike].to_i,option_params[:riskfree].to_i,option_params[:dividend].to_f,option_params[:term].to_f,option_params[:volatility].to_f) 
    @option.update_attributes(:call_price => @prices[0] ,:put_price => @prices[1]) 
    respond_to do |format|
      if @option.update_attributes(params[:option])
        format.html { redirect_to @option, notice: 'Option was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render 'edit' }
        format.json { render json: @option.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /options/1
  # DELETE /options/1.json
  def destroy
    @option = Option.find(params[:id])
    @option.destroy

    respond_to do |format|
      format.html { redirect_to options_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/views/home/index.html.erb
<title>Welcome</title>

<div class="row">
	<div class="span6 offset3">
		<% unless current_user %>
			<h1>Create Account</h1>
			<%= link_to "Create Account", new_user_registration_path  %>
		<% end %>
		<% if current_user %>
			<h1>Start Calculating</h1>
			<%= link_to "Create Option Calc", options_path %>
		<% end %>
	</div><!-- .span6 offset3 -->
		
</div><!-- .row -->

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
			<%#= link_to "Black-Scholes Calculator", root_path, :class => "brand" %>
			<%= link_to "Home page", root_path, :class => "brand" %>
      
      <div class="nav-collapse">
        <ul class="nav pull-right">
          <li><%= link_to "My Calcs", options_path %></li>
					<% if user_signed_in? %>
						
						<li class ="divider-vertical"></li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-user icon-white"></i> <%= current_user.email %> <b class="caret"></b></a>
					    <ul class="dropdown-menu">
					      <li><%= link_to edit_user_registration_path(current_user) do %>
					      	<i class="icon-cog"></i> Profile
								<% end %>
								</li>
								<li class="divider"></li>
					      <li><%= link_to destroy_user_session_path, method: :delete do %>
									<i class="icon-remove"></i> Logout
								<% end %>
								</li>
					    </ul>
					   </li>				
						<% else %>
					  <li><%= link_to "Sign up", new_user_registration_path %></li>
					  <li><%= link_to "Login", new_user_session_path %></li>
					<% end %>			

        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Options</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<div class="container">
	<%= render 'layouts/navbar' %>
	
	<div class="row">
		<div class="span12">
			<% flash.each do |name, msg| %>
				<%= content_tag :div, :class => "alert alert-#{name}" do %>
					<a class="close" data-dismiss="alert">×</a>
					<h4 class="alert-heading"><%= name.capitalize %>!</h4>
					<ul class="unstyled">
						<li><%= msg %></li>
					</ul>
				<% end %>
			<% end %>
		</div><!-- .span12 -->
	</div><!-- .row -->

	
	<%= yield %>	
</div><!-- .container -->


</body>
</html>

app/views/options/_form.html.erb
<%= simple_form_for(@option, :html => { :class => 'form-horizontal' }) do |f| %>
<%= f.error_notification %>

<div class="inputs">
  <%= f.input :title, :wrapper => :prepend, :label => "Title" do %>
    <%= f.input_field :title %>
	<% end %>
	<%= f.input :price, :wrapper => :prepend, :label => "Market price" do %>
		<%= content_tag :span, "$", :class => "add-on" %>
	    <%= f.input_field :price %>
	<% end %>
  <%= f.input :strike, :wrapper => :prepend, :label => "Exercice price" do %>
		<%= content_tag :span, "$", :class => "add-on" %>
	    <%= f.input_field :strike %>
	<% end %>
	<%= f.input :price, :wrapper => :append, :label => "Expected life" do %>
	    <%= f.input_field :term  %>
			<%= content_tag :span, "yrs", :class => "add-on" %>
	<% end %>
	<%= f.input :price, :wrapper => :append, :label => "Volatility" do %>
    <%= f.input_field :volatility %>
		<%= content_tag :span, "%", :class => "add-on" %>
	<% end %>
	<%= f.input :dividend, :wrapper => :prepend, :label => "Dividend yield" do %>
		<%= f.input_field :dividend %>
		<%= content_tag :span, "%", :class => "add-on" %>  
	<% end %>
	<%= f.input :riskfree, :wrapper => :prepend, :label => "Risk free rate" do %>
    <%= f.input_field :riskfree %>		
		<%= content_tag :span, "%", :class => "add-on" %>
	<% end %>
</div>


  <div class="form-actions">
    <%= f.button :submit, :label => "Calculate", :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                options_path, :class => 'btn' %>
  </div>
<% end %>

app/views/options/_tombstone.html.erb
<div class="tombstone_container">
<% @options.each do |option| %>
<div class="tombstone">
	<h2 class="title"><%= option.title %></h2>
	<dl class="dl-horizontal">
	  <dt><strong>Price:</strong></dt>
	  <dd><%= number_to_currency(option.price, :precision => 5) %></dd>
	  <dt><strong>Strike:</strong></dt>
	  <dd><%= number_to_currency(option.strike, :precision => 5) %></dd>
	  <dt><strong>Expected term:</strong></dt>
	  <dd><%= option.term %> years</dd>
	  <dt><strong>Volatility:</strong></dt>
	  <dd><%= number_to_percentage(option.volatility, :precision => 5) %></dd>
	  <dt><strong>Dividend yield:</strong></dt>
	  <dd><%= number_to_percentage(option.dividend, :precision => 5) %></dd>
	  <dt><strong>Risk-free rate:</strong></dt>
	  <dd><%= number_to_percentage(option.riskfree, :precision => 5) %></dd>
	  <dt><strong>Call price</strong></dt>
	  <dd><%= number_to_currency(option.call_price, :precision => 5) %></dd>
	  <dt><strong>Put price</strong></dt>
	  <dd><%= number_to_currency(option.put_price, :precision => 5) %></dd>
	</dl>
	<div class="pull-right">
		<%= link_to edit_option_path(option), :title => "Edit" do %>
			<i class="icon icon-edit"></i>
		<% end %> | 
		<%= link_to option_path(option), :method => :delete, :title => "trash", :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) do %>
			<i class="icon icon-trash"></i>
		<% end %>
	</div><!-- .pull-right -->

</div>
<% end %>
</div>

app/views/options/edit.html.erb
<%- model_class = @option.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>

<div class="row">
	<div class="span6">
		<%= render 'form' %>
	</div><!-- .span6 -->
	<div class="span6" id="description">
		
	</div><!-- .span6 -->
</div><!-- .row -->

app/views/options/index.html.erb
<%- model_class = Option.new.class -%>
<title>My Calculations</title>
<div class="page-header">
  <h1>Option Calculations</h1>
</div>
<div class="row">
	<div class="pull-right">
		<%= will_paginate(@options) %>					
	</div><!-- .pull-right -->
</div><!-- .row -->

<div class="row">
	<div class="pull-right">
		<%= link_to new_option_path, :class => 'btn btn-primary btn-large' do %>
			<i class="icon icon-plus"></i> Create
		<% end %>		
	</div><!-- .pull-right -->
</div><!-- .row -->


<%= render 'tombstone' %>

app/views/options/new.html.erb
<%- model_class = @option.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/options/show.html.erb
<%- model_class = @option.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= number_to_currency(@option.price, :precision => 5) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:strike) %>:</strong></dt>
  <dd><%= number_to_currency(@option.strike, :precision => 5) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:term) %>:</strong></dt>
  <dd><%= @option.term %> years</dd>
  <dt><strong><%= model_class.human_attribute_name(:volatility) %>:</strong></dt>
  <dd><%= number_to_percentage(@option.volatility, :precision => 5) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:dividend) %>:</strong></dt>
  <dd><%= number_to_percentage(@option.dividend, :precision => 5) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:riskfree) %>:</strong></dt>
  <dd><%= number_to_percentage(@option.riskfree, :precision => 5) %></dd>
  <dt><strong>call price</strong></dt>
  <dd><%= number_to_currency(@option.call_price, :precision => 5) %></dd>
  <dt><strong>put price</strong></dt>
  <dd><%= number_to_currency(@option.put_price, :precision => 5) %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              options_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_option_path(@option), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              option_path(@option),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>